language: php

php:
  - 5.4

mysql:
  database: data_starter
  username: root
  encoding: utf8

install:
  - pwd
  - mysql -e 'create database data_starter;'
  - sudo apt-get update > /dev/null
  - sudo apt-get --quiet=2 install php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:6.*
  - drush dl registry_rebuild
  - cd $TRAVIS_BUILD_DIR

script:
# Build website
  - cd docroot
  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1/data_starter --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - cd ../scripts; ./rebuild-nucivic-data.sh
