language: php

php:
  - 5.6

mysql:
  database: dkan_travis
  username: root
  encoding: utf8

install:
  - mysql -e 'create database dkan_travis;'
  - sudo apt-get update > /dev/null
  - sudo apt-get --quiet=2 install php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master
  - composer global require --no-interaction youngj/httpserver:*

before_script:
  # Install DKAN
  - cd ~
  - git clone https://github.com/NuCivic/dkan-drops-7.git
  - cd dkan-drops-7

  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush cc all --yes
  - cp -r /home/travis/build/NuCivic/dkan_harvest sites/all/modules/.
  - drush dl -y migrate-7.x-2.x
  - drush en -y migrate
  - cd sites/all/modules
  - git clone https://github.com/NuCivic/dkan_migrate_base.git --branch 7.x-1.x
  - drush dis -y dkan_default_content
  - drush pm-uninstall -y dkan_default_content
  - drush en -y dkan_migrate_base
  - drush en -y dkan_harvest
  - drush en -y dkan_harvest_test
  - drush en -y dkan_harvest_example
  - cd dkan_harvest/test
  - composer install

script:
  - bin/phpunit --bootstrap=boot.php DKANHarvestBaseTest.php
