language: php
sudo: false

php:
  - 5.5

mysql:
  database: dkan_travis
  username: root
  encoding: utf8

install:
  - cd test
  - composer install
  - mysql -e 'create database dkan_travis;'

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master
  - composer global require --no-interaction youngj/httpserver:*

before_script:
  # Install DKAN
  - cd ~
  - git clone https://github.com/NuCivic/dkan.git
  - git clone https://github.com/NuCivic/dkan-drops-7.git
  - cd dkan-drops-7

  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush cc all --yes

  - cp -r /home/travis/build/NuCivic/dkan_migrate_base sites/all/modules/.
  - cd sites/all/modules
  - git clone https://github.com/NuCivic/open_data_federal_extras.git
  - drush en -y open_data_federal_extras
  - drush en -y dkan_migrate_base
  - drush en -y dkan_migrate_base_example
  - cd dkan_migrate_base/test
  - composer install

script:
  - bin/phpunit --bootstrap=boot.php DKANMigrateBaseTest.php
